name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI checks
        run: pnpm ci

      - name: Temp - update coverage branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: coverage
          FOLDER: coverage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Test coverage from {sha}'
          SKIP_EMPTY_COMMITS: true
